config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images
  has_many :notifications, dependent: :destroy

  validates :text, presence: true

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and tweet_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      tweet_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(3)
  end

  def search
    @tweets = Tweet.where('text LIKE(?)', "%#{params[:keyword]}%").page(params[:page]).per(3)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = @tweet.comments.build
    @comments = @tweet.comments.includes(:user)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  private
    def tweet_params
      params.require(:tweet).permit(:text, images: []).merge(user_id: current_user.id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.haml
.contents
  = render "side-bar"
  .contents__right
    .contents__right__tweets
      - if current_page?(new_tweet_path)
        新規作成
      - else
        編集
      = form_with model: tweet, local: true do |form|
        %p.contents__right__tweets__form-text
          Text
        = form.text_area  :text, class: "contents__right__tweets__form-textarea"
        - if tweet.errors.any?
          .contents__right__tweets__form-text-error
            - tweet.errors.full_messages.each do |message|
              = message
        = form.file_field :images, multiple: true, class: "contents__right__tweets__form-image"
        = form.submit "作成", class: "contents__right__tweets__form-submit"

app/views/tweets/_side-bar.html.haml
.contents__left
  = link_to "断捨list", root_path, class: "contents__left__title"
  - if user_signed_in?
    = link_to "#{current_user.nickname}", user_path(current_user), class: "contents__left__user-name"
    .contents__left__follows
      .contents__left__follows__following
        .contents__left__follows__following__text
          = link_to "フォロー中", following_user_path(current_user)
        .contents__left__follows__following__count
          = current_user.following.count
      .contents__left__follows__followers
        .contents__left__follows__followers__text
          = link_to "フォロワー", followers_user_path(current_user)
        .contents__left__follows__followers__count
          = current_user.followers.count
    = link_to notifications_path do
      通知
      - if unchecked_notifications.any?
        あるよ
      - else
        ないよ
    = link_to "お気に入り", root_path, class: "contents__left__content"
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "contents__left__content"
    = link_to "マイページ", user_path(current_user), class: "contents__left__content"
  - else
    = link_to "新規登録", new_user_registration_path, class: "contents__left__content"
    = link_to "ログイン", new_user_session_path, class: "contents__left__content"
  = link_to "新規投稿", new_tweet_path, class: "contents__left__content"
  = form_with(url: search_tweets_path, local: true, method: :get) do |form|
    = form.text_field :keyword
    = form.submit

app/views/tweets/_tweet.html.haml
.contents__right
  .contents__right__tweets
    - tweets.each do |tweet|
      .contents__right__tweets__tweet
        %p.contents__right__tweets__tweet__user-nickname
          = link_to "#{tweet.user.nickname}", user_path(tweet.user), class: "contents__right__tweets__tweet__user-nickname_link"
        %p.contents__right__tweets__tweet__text
          = tweet.text
        - if tweet.images
          - tweet.images.each do |image|
            = image_tag image, class: "contents__right__tweets__tweet__image"
        .contents__right__tweets__tweet__option
          %div{class: "likes", id: "like-#{tweet.id}"}
            = render "likes/like", tweet: tweet
          = link_to "詳細", tweet_path(tweet)
          - if user_signed_in? && current_user.id == tweet.user_id
            = link_to "編集", edit_tweet_path(tweet)
            = link_to "削除", tweet_path(tweet), method: :delete, data: { confirm: "削除しますか？" }
    .contents__right__tweets__paginate
      = paginate(tweets)

app/views/tweets/edit.html.haml
= render "form", tweet: @tweet

app/views/tweets/index.html.haml
.contents
  = render "side-bar"
  = render "tweet", tweets: @tweets

app/views/tweets/new.html.haml
= render "form", tweet: @tweet

app/views/tweets/search.html.haml
.contents
  = render "side-bar"
  = render "tweet", tweets: @tweets

app/views/tweets/show.html.haml
.contents
  = render "side-bar"
  .contents__right
    .contents__right__tweets
      .contents__right__tweets__tweet
        %p.contents__right__tweets__tweet__user-nickname
          = link_to "#{@tweet.user.nickname}", user_path(@tweet.user), class: "contents__right__tweets__tweet__user-nickname_link"
        %p.contents__right__tweets__tweet__text
          = @tweet.text
        - if @tweet.images
          - @tweet.images.each do |image|
            = image_tag image, class: "contents__right__tweets__tweet__image"
        .contents__right__tweets__tweet__option
          = link_to "詳細", tweet_path(@tweet)
          - if user_signed_in? && current_user.id == @tweet.user_id
            = link_to "編集", edit_tweet_path(@tweet)
            = link_to "削除", tweet_path(@tweet), method: :delete

      - if current_user
        = form_with(model: [@tweet, @comment], local: true) do |form|
          .contents__right__tweets__form-comment-error
            = flash[:danger]
          = form.text_field :text, placeholder: "コメント", class: "contents__right__tweets__form-comment-text"
          = form.submit "送信", class: "contents__right__tweets__form-comment-submit"
      - if @comments
        - @comments.each do |comment|
          .contents__right__tweets__comments
            = link_to "#{comment.user.nickname}", user_path(comment.user), class: "contents__right__tweets__comments__user-name"
            .contents__right__tweets__comments__text
              = comment.text
            = link_to "削除", tweet_comment_path(tweet_id: comment.tweet_id, id: comment), method: :delete, class: "contents__right__tweets__comments__delete", data: { confirm: "削除しますか？" }